-- Databaseと文字コードの指定
USE localdb;
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

-- テーブル削除クエリ
DROP TABLE IF EXISTS users;

-- ユーザ
CREATE TABLE users (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);